import { Montserrat, Unbounded } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

import Footer from "@/components/footer/FooterComp";
import Header from "@/components/header/HeaderComp";

// Montserrat for body text
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// Unbounded for headings or bold elements
const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

// VCR OSD Mono for retro-styled elements
const vcrOsdMono = localFont({
  src: "./fonts/VCR_OSD_MONO.ttf",
  variable: "--font-vcr-osd-mono",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata = {
  metadataBase: new URL("http://muhammadadil.work.gd"),
  title: {
    default: "Adil's Portfolio",
    template: "%s | Adil's Portfolio",
  },
  description: "Welcome to Adil's portfolio showcasing projects, skills, and achievements.",
  openGraph: {
    siteName: "Adil's Portfolio",
    type: "website",
    title: "Adil's Portfolio",
    description: "Explore Adil's portfolio of projects, designs, and experiences.",
  },
  twitter: {
    card: "summary_large_image",
    title: "Adil's Portfolio",
    description: "Welcome to Adil's personal portfolio website.",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${montserrat.variable} ${unbounded.variable} ${vcrOsdMono.variable} antialiased max-w-[980px] m-auto px-5 lg:px-0 overflow-x-hidden bg-[#080708]`}
      // className={`${montserrat.variable} ${unbounded.variable} ${vcrOsdMono.variable} antialiased px-6 sm:px-10 md:px-14 lg:px-20 bg-[#080708]`}
      >
        <div>
          <Header />
          <main className="flex flex-col pb-20 gap-10 md:gap-20">
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}